Repository react-native-webview/react-native-webview, pull requests merged in 2018-09, with the labels that each got.

#34 try reuse Android tooling config from React Native
  android/build.gradle
Labels: question

#41 Imported https://github.com/facebook/react-native/pull/20366
  android/src/main/java/com/reactnativecommunity/webview/RCTWebViewManager.java
Labels: migrated

#56 Migrate Documentation
  README.md
  docs/Custom-Android.md
  docs/Custom-iOS.md
  docs/Getting-Started.md
  docs/Guide.md
  docs/Reference.md
Labels: documentation
