Repository react-native-webview/react-native-webview, pull requests merged in 2018-11, with the labels that each got.

#95 Add typescript definitions
  package.json
  typings/index.d.ts
  yarn.lock
Labels: Hacktoberfest, ready to publish

#112 Add 'userAgent' property to the iOS WKWebView.
  docs/Reference.md
  ios/RNCWKWebView.h
  ios/RNCWKWebView.m
  ios/RNCWKWebViewManager.m
  js/WebView.ios.js
  js/WebViewTypes.js
Labels: ready to publish

#129 Fixed for supporting mediaPlaybackRequiresUserAction option under iOS 10.
  ios/RNCWKWebView.m
Labels: ready to publish

#132 Add docs for missing props which do something
  docs/Reference.md
Labels: ready to publish

#134 Add fix for keyboard dismiss leaving viewport shifted in iOS 12
  ios/RNCWKWebView.m
Labels: WKWebview, bug, ready to publish

#146 Added contributing guide and empyrical link
  README.md
  docs/Contributing.md
Labels: documentation

#143 Fix the message handle bug.
  ios/RNCWKWebView.m
Labels: ready to publish

#60 Fix #33 Support Android file upload
  android/src/main/AndroidManifest.xml
  android/src/main/java/com/reactnativecommunity/webview/RNCWebViewFileProvider.java
  android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
  android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java
  android/src/main/java/com/reactnativecommunity/webview/RNCWebViewPackage.java
  android/src/main/res/xml/file_provider_paths.xml
  docs/Guide.md
  js/WebView.android.js
  js/WebView.ios.js
Labels: ready to publish
