Repository react-native-webview/react-native-webview, pull requests merged in 2019-01, with the labels that each got.

#217 chore(docs): Add testimonial to README
  README.md
Labels: documentation

#225 add style doc in reference.md
  docs/Reference.md
Labels: ready to publish

#203 Add file download support for Android
  android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
  android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java
  docs/Guide.md
Labels: ready to publish

#138 Add shared process pool so cookies and localStorage are shared across webviews in iOS
  ios/RNCWKProcessPoolManager.h
  ios/RNCWKProcessPoolManager.m
  ios/RNCWKWebView.h
  ios/RNCWKWebView.m
  ios/RNCWKWebViewManager.m
  ios/RNCWebView.xcodeproj/project.pbxproj
  js/WebView.ios.js
  js/WebViewTypes.js
Labels: ready to publish

#164 [android] replace deprecated `WebView.PictureListener`->`onContentSizeChange` impl
  android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
Labels: need testing before merge

#148 Add incognito prop to iOS WKWebview
  docs/Reference.md
  ios/RNCWKWebView.h
  ios/RNCWKWebView.m
  ios/RNCWKWebViewManager.m
  js/WebView.ios.js
  js/WebViewTypes.js
Labels: need testing before merge

#147 Add "Frame load interrupted" error handling for OAuth for RNCWKWebView
  ios/RNCWKWebView.m
Labels: need testing before merge

#173 Update webview property when component prop changes
  ios/RNCWKWebView.m
Labels: need testing before merge

#273 Fix for issue #266
  android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
Labels: ready to publish

#152 [feat] Add `cacheEnabled` prop
  android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
  docs/Reference.md
  ios/RNCWKWebView.h
  ios/RNCWKWebView.m
  ios/RNCWKWebViewManager.m
  js/WebView.android.js
  js/WebView.ios.js
  js/WebViewTypes.js
Labels: ready to publish
