Repository react-native-webview/react-native-webview, pull requests merged in 2019-02, with the labels that each got.

#296 Reapplied #134 with additional checks to tackle unintentional scrolls
  ios/RNCWKWebView.m
Labels: need testing before merge

#141 [wkwebview] create api to allow clients to present a client credential for authentication
  docs/Custom-iOS.md
  ios/RNCWKWebView.h
  ios/RNCWKWebView.m
Labels: need testing before merge

#250 Show/hide WebView scroll indicators
  android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
  docs/Reference.md
  ios/RNCUIWebViewManager.m
  ios/RNCWKWebView.h
  ios/RNCWKWebView.m
  ios/RNCWKWebViewManager.m
  js/WebView.android.js
  js/WebView.ios.js
  js/WebViewTypes.js
Labels: need testing before merge

#158 Don't allow the scrollView to scroll when `scrollEnabled={false}`.
  docs/Reference.md
  ios/RNCWKWebView.m
Labels: bug, ready to publish

#275 fix(android:scalesPageToFit): scalesPageToFit does not work as intended , especially for large jpg and png images.
  android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
Labels: enhancement, ready to publish

#357 Android: Support file extensions in file input accept attributes
  android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java
Labels: ready to publish
