Repository react-native-webview/react-native-webview, pull requests merged in 2019-08, with the labels that each got.

#524 Add incognito prop to Android RNCWebViewManager
  android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
  docs/Reference.md
  src/WebViewTypes.ts
Labels: Maintainer: ready to publish

#567 Add focus functionality for devices without touch screen
  android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
  index.d.ts
  src/WebView.android.tsx
  src/WebView.ios.tsx
  src/WebViewTypes.ts
Labels: Help wanted, good first issue

#730 Adding a `contentInsetAdjustmentBehavior` prop to the WebView for iOS.
  docs/Reference.md
  ios/RNCWKWebView.m
  ios/RNCWKWebViewManager.m
  src/WebViewTypes.ts
Labels: Maintainer: need testing
