Repository react-native-webview/react-native-webview, pull requests merged in 2019-03, with the labels that each got.

#144 Adds guide for handling navigation state changes
  docs/Guide.md
Labels: documentation, ready to publish

#395 fix flow error
  package.json
  yarn.lock
Labels: ready to publish

#382 Add multiple file upload selection in the docs
  docs/Guide.md
Labels: ready to publish

#393 Add typescript definition for isFileUploadSupported
  typings/index.d.ts
Labels: ready to publish

#389 feat: add prop `directionalLockEnabled` for iOS
  docs/Reference.md
  ios/RNCUIWebViewManager.m
  ios/RNCWKWebView.h
  ios/RNCWKWebView.m
  ios/RNCWKWebViewManager.m
  js/WebView.ios.js
  js/WebViewTypes.js
  typings/index.d.ts
Labels: need testing before merge

#434 fix(android): Do not hold a strong reference to native module in package
  android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
  android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java
  android/src/main/java/com/reactnativecommunity/webview/RNCWebViewPackage.java
Labels: need testing before merge

#414 Android scaling issue
  android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
  src/WebViewTypes.ts
Labels: User: question
