Repository react-native-webview/react-native-webview, pull requests merged in 2020-08, with the labels that each got.

#1480 feat(android): WebView crash handling
  android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
  android/src/main/java/com/reactnativecommunity/webview/events/TopRenderProcessGoneEvent.kt
  docs/Reference.md
  src/WebView.android.tsx
  src/WebViewTypes.ts
Labels: Maintainer: ready to publish

#1447 Fix incognito invoking clear cookies when not enabled
  android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
Labels: Stale

#1537 feat(events): Add isTopFrame to shouldStartLoadForRequest
  android/src/main/java/com/reactnativecommunity/webview/events/TopShouldStartLoadWithRequestEvent.kt
  apple/RNCWebView.m
  docs/Reference.md
  src/WebViewShared.tsx
  src/WebViewTypes.ts
Labels: Maintainer: ready to publish

#1265 feat(iOS): Add the pull to refresh
  apple/RNCWebView.h
  apple/RNCWebView.m
  apple/RNCWebViewManager.m
  docs/Reference.md
  src/WebViewTypes.ts
Labels: Stale, User: question

#1536 Convert ContentInsetAdjustmentBehavior from an enum back to a string union type
  src/WebViewTypes.ts
Labels: Maintainer: ready to publish

#1590 feat(android): Synchronous onShouldStartLoadWithRequest
  android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
  android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java
  src/WebView.android.tsx
Labels: Maintainer: ready to publish
